Repository danielnachun/recipe_staging, pull requests merged in 2024-02, with the labels that each got.

#1382 add lrzip
  lrzip/build.sh
  lrzip/meta.yaml
Labels: upload

#1358 add svg2pdf
  libsvg-cairo/0001-use-newer-autotools.patch
  libsvg-cairo/build.sh
  libsvg-cairo/meta.yaml
  libsvg/0001-use-newer-autotools.patch
  libsvg/0002-Fix-undefined-symbol-png_set_gray_1_2_4_to_8.patch
  libsvg/build.sh
  libsvg/meta.yaml
  svg2pdf/build.sh
  svg2pdf/meta.yaml
Labels: upload

#1412 yabai 6.0.7
  yabai/meta.yaml
Labels: upload

#1413 add qemu
  colima/build.sh
  colima/meta.yaml
  docker-buildx/build.sh
  docker-buildx/meta.yaml
  docker-credential-helper/build.sh
  docker-credential-helper/meta.yaml
  docker/build.sh
  docker/meta.yaml
  go-md2man/build.sh
  go-md2man/meta.yaml
  gvproxy/build.sh
  gvproxy/meta.yaml
  lima/build.sh
  lima/meta.yaml
  podman-remote/build.sh
  podman-remote/meta.yaml
  spice-protocol/build.sh
  spice-protocol/meta.yaml
  vde/build.sh
  vde/meta.yaml
Labels: upload

#1391 add fourmolu
  .github/centos7_container.df
  .github/workflows/conda_mambabuild_linux-64.yml
  fourmolu/build.sh
  fourmolu/conda_build_config.yaml
  fourmolu/meta.yaml
Labels: upload, centos7

#1395 add stylish-haskell
  stylish-haskell/630ac1bf035a95cda0295ce669de06da17b91c0f.patch
  stylish-haskell/build.sh
  stylish-haskell/meta.yaml
Labels: upload, centos7

#1393 add haskell-language-server
  haskell-language-server/build.sh
  haskell-language-server/meta.yaml
Labels: upload, centos7

#1392 add hadolint
  hadolint/0001-fix-ghc-9.8-build.patch
  hadolint/build.sh
  hadolint/meta.yaml
Labels: upload, centos7

#1390 add dhall
  dhall/0001-fix-ghc-9.8-build.patch
  dhall/build.sh
  dhall/meta.yaml
Labels: upload, centos7

#1374 add ghc
  .github/workflows/conda_mambabuild_linux-64.yml
  ghc/build.sh
  ghc/hello.hs
  ghc/meta.yaml
  ghc/post-link.sh
Labels: centos7

#1418 add r-softimpute
  r-softimpute/bld.bat
  r-softimpute/build.sh
  r-softimpute/meta.yaml
Labels: upload

#1419 add ocaml
  ocaml/0001-prefix-fix.patch
  ocaml/activate.sh
  ocaml/build.sh
  ocaml/deactivate.sh
  ocaml/meta.yaml
  ocaml/prefix_fix.diff
  ocaml/prefix_fix_5.0.0.diff
Labels: upload

#1375 add dune
  dune/build.sh
  dune/meta.yaml
Labels: upload

#1420 add hadolint
  hadolint/meta.yaml
Labels: centos7

#1426 add cgrep
  cgrep/build.sh
  cgrep/cabal.project
  cgrep/meta.yaml
Labels: upload, centos7

#1427 add hlint
  hlint/build.sh
  hlint/meta.yaml
Labels: upload, centos7

#1429 add shake
  shake/build.sh
  shake/meta.yaml
Labels: upload, centos7

#1430 add alex
  alex/build.sh
  alex/meta.yaml
Labels: upload, centos7

#1432 Release susieR 0.14.4
  r-susier/meta.yaml
Labels: upload

#1446 ronn: make noarch
  ronn/build.sh
  ronn/meta.yaml
Labels: upload

#1449 ghc: enable for Apple Silicon
  ghc/meta.yaml
Labels: ci-skip

#1451 ghc: fix dependencies
  ghc/meta.yaml
Labels: ci-skip

#1452 ghc: fix build
  ghc/build.sh
Labels: ci-skip

#1453 ghc: fix build
  ghc/build.sh
Labels: ci-skip

#1455 ldc 1.36.0
  ldc/build.sh
  ldc/meta.yaml
Labels: upload

#1497 powershell 7.4.1
  powershell/meta.yaml
Labels: upload

#1498 gvproxy 0.7.2
  gvproxy/build.sh
  gvproxy/meta.yaml
Labels: upload

#1501 podman 4.9.2
  podman-remote/meta.yaml
Labels: upload

#1499 lima 0.20.1
  lima/build.sh
  lima/conda_build_config.yaml
  lima/meta.yaml
Labels: upload

#1505 colima 0.6.8
  colima/meta.yaml
Labels: upload

#1534 add prsice
  prsice/0001-devendor-eigen.patch
  prsice/build.sh
  prsice/meta.yaml
Labels: upload

#1728 rnaseqc: restrict boost version
  rnaseqc/meta.yaml
Labels: upload

#1732 paket: make noarch
  paket/build.sh
  paket/meta.yaml
Labels: upload

#1729 cake: make noarch
  cake/build.sh
  cake/meta.yaml
Labels: upload

#1733 swing: make noarch
  swing/meta.yaml
Labels: upload

#1734 opal: make noarch
  opal/meta.yaml
Labels: upload

#1730 fake: make noarch
  fake/build.sh
  fake/meta.yaml
Labels: upload

#1740 r-genetics.binaries: make noarch
  r-genetics.binaries/meta.yaml
Labels: upload

#1743 cyvcf2: use openssl 3.1
  cyvcf2/meta.yaml
Labels: upload

#1741 metaxcan: make noarch
  metaxcan/meta.yaml
Labels: upload

#1764 otters: make noarch
  otters/meta.yaml
Labels: upload

#1765 fusion: make noarch
  fusion/build.sh
  fusion/meta.yaml
  gcta_nr_robust/build.sh
  gcta_nr_robust/meta.yaml
Labels: upload

#1760 tigar: make noarch
  tigar/meta.yaml
Labels: upload

#1486 add pylyzer
  pylyzer/meta.yaml
Labels: upload
